{
 "title": "Oracle Database",
 "tags": [ "Oracle DB" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "DB Name",
    "query": {
     "query": "label_values(oracledb_up, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d" }
  ]
 },
 "panels": [
  {
   "title": "Database status",
   "type": "stat",
   "description": "Database Status (Online or Offline)",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_up{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Process count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_process_count{instance=\"$host\"}",
     "legendFormat": "{{descr}} - Process count"
    }
   ]
  },
  {
   "title": "User commits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_activity_user_commits{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "User rollback",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_activity_user_rollbacks{instance=\"$host\"}",
     "legendFormat": "{{descr}} - User rollback"
    }
   ]
  },
  {
   "title": "Tablespace Usage",
   "type": "table",
   "gridPos": { "h": 30, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "oracledb_tablespace_max_bytes{instance=~\"$host\"}",
     "legendFormat": "{{ tablespace }}"
    },
    {
     "expr": "oracledb_tablespace_free{instance=~\"$host\"}",
     "legendFormat": "{{ tablespace }}"
    },
    {
     "expr": "oracledb_tablespace_bytes{instance=~\"$host\"}",
     "legendFormat": "{{ tablespace }}"
    },
    {
     "expr": "100 - ((oracledb_tablespace_free{instance=~\"$host\"} * 100) / oracledb_tablespace_max_bytes{instance=~\"$host\"})",
     "legendFormat": "{{ tablespace }}"
    }
   ]
  },
  {
   "title": "Number of Processes",
   "type": "stat",
   "description": "Generic counter metric from v$resource_limit view in Oracle (current value).",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_resource_current_utilization{instance=~\"$host\",resource_name=\"processes\"}"
    }
   ]
  },
  {
   "title": "Number of Sessions",
   "type": "stat",
   "description": "Generic counter metric from v$resource_limit view in Oracle (current value).",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_resource_current_utilization{instance=~\"$host\",resource_name=\"sessions\"}"
    }
   ]
  },
  {
   "title": "Active sessions (USER)",
   "type": "stat",
   "description": "Active sessions (USER)",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_sessions_value{instance=\"$host\",status=\"ACTIVE\",type=\"USER\"}"
    }
   ]
  },
  {
   "title": "Last Scrap Status",
   "type": "stat",
   "description": "Whether the last scrape of metrics from Oracle DB resulted in an error (1 for error, 0 for success).",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_exporter_last_scrape_error{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Concurrent wait time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_concurrency{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Commit wait time",
   "type": "timeseries",
   "description": "Commit wait time",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_commit{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Application wait time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_application{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Network wait time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_network{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "System I/O wait",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_system_io{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Configure wait time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_configuration{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "User I/O wait",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_user_io{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Scheduler wait time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_scheduler{instance=\"$host\"}"
    }
   ]
  }
 ]
}