apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    creationPolicy: Owner
    template:
        type: opaque
        data:
          adminuser: "admin"
          adminpass: "{{ `{{ .adminpass }}` }}"
  data:
  - secretKey: adminpass
    remoteRef:
      key: secret/monitoring
      property: grafanaAdminPassword

