apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: crcreds
spec:
  externalSecretName: crcreds
  refreshTime: 1h
  namespaceSelector: {}
  externalSecretSpec:
    refreshInterval: "1h"
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    target:
      template:
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: "{{ .crcreds }}"
      name: crcreds
      creationPolicy: Owner
    data:
    - secretKey: crcreds
      remoteRef:
        key: secret/jfrog
        property: crcreds
