#ref : https://external-secrets.io/v0.5.9/api-clustersecretstore/
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.addr"
      path: "secret"
      version: "v2"
      caBundle: ""
      auth:
        tokenSecretRef:
          name: "external-secrets-vault-read-token"
          namespace: "external-secrets"
          key: "vault-token"
