apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mega-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: test-secret
    creationPolicy: Owner
  data:
  - secretKey: testKey
    remoteRef:
      key: secret/my_secret_path
      property: mega-key
