FROM alpine:3

ARG KUBE_VERSION
ARG HELM_VERSION
ARG HELM_SECRETS_VERSION
ARG VAULT_VERSION
ARG YQ_VERSION
ARG BUILD_DATE
ARG VERSION

LABEL maintainer="amine-errahmani" \
      org.label-schema.schema-version=${VERSION} \
      org.label-schema.build-date=${BUILD_DATE} \
      org.label-schema.name="HelmKubeVault" \
      org.label-schema.description="helm ." \
      org.label-schema.vcs-url="https://github.com/amine-errahmani/devops-tools"

RUN apk -U upgrade \
    && apk add --no-cache ca-certificates bash git openssh curl gettext jq \
    && mkdir /config \
    && chmod g+rwx /config /root

RUN wget -q https://storage.googleapis.com/kubernetes-release/release/v${KUBE_VERSION}/bin/linux/amd64/kubectl -O /usr/local/bin/kubectl \
    && chmod +x /usr/local/bin/kubectl \
    && kubectl version --client .

RUN wget -q https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > /usr/local/bin/helm \
    && chmod +x /usr/local/bin/helm \
    && helm version \
    && helm plugin install https://github.com/jkroepke/helm-secrets --version v${HELM_SECRETS_VERSION} \
    && helm secrets version \
    && helm plugin install https://github.com/databus23/helm-diff \
    && helm diff version \
    && helm repo add "stable" "https://charts.helm.sh/stable" --force-update 

RUN wget -q https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_amd64 -O /usr/local/bin/yq \
    && chmod +x /usr/local/bin/yq

RUN wget -q https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip \
    && unzip vault_${VAULT_VERSION}_linux_amd64.zip \
    && mv vault /usr/local/bin/ \
    && rm -rf /tmp/* \
    && chmod +x /usr/local/bin/vault \
    && vault version 

WORKDIR /config

CMD bash