apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "oracledb-exporter.fullname" . }}-dsn-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ include "oracledb-exporter.fullname" . }}-dsn-secret
    creationPolicy: Owner
  data:
  - secretKey: dsn
    remoteRef:
      key: monitoring/oracle
      property: {{ .Values.dsnSecretKey }}
