---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-vault-issuer
  namespace: cert-manager
spec:
  vault:
    path: pki_intermediate_ca_core/sign/generic_server_cert
    server: https://vault.addr
    caBundle: ""
    auth:
      appRole:
        path: approle
        roleId: approle_id
        secretRef:
          key: secretId
          name: cert-manager-vault-approle

          