apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-objstore-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: thanos-objstore-config
    creationPolicy: Owner
    template:
        type: opaque
        data:
          objstore.yml: |
            type: AZURE
            config:
              storage_account: "{{ `{{ .saname }}` }}"
              storage_account_key: "{{ `{{ .sakey }}` }}"
              container: "{{ `{{ .sacontainer }}` }}"
              endpoint: ""
  data:
  - secretKey: saname
    remoteRef:
      key: secret/monitoring/thanos
      property: saName
  - secretKey: sakey
    remoteRef:
      key: secret/monitoring/thanos
      property: saKey
  - secretKey: sacontainer
    remoteRef:
      key: secret/monitoring/thanos
      property: saContainer

