kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: file.csi.azure.com
mountOptions:
  - mfsymlinks
  - actimeo=30
  - dir_mode=0777
  - file_mode=0777
  - cache=strict
parameters:
  storageAccount: <storage_account>
allowVolumeExpansion: true
volumeBindingMode: Immediate