apiVersion: v1
kind: Service
metadata:
  name: {{ include "namematching.fullname" . }}
  labels:
    {{- include "namematching.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "namematching.selectorLabels" . | nindent 4 }}
