{
 "title": "Linux Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node:",
    "query": {
     "query": "label_values(node_boot_time_seconds, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\"} - node_boot_time_seconds{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Environment",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_boot_time_seconds{instance=~\"$node\"}",
     "legendFormat": "{{ Environment }}, {{Solution}}"
    }
   ]
  },
  {
   "title": "Solution",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_boot_time_seconds{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Department",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_boot_time_seconds{instance=~\"$node\"}",
     "legendFormat": "{{ Environment }}, {{Solution}}"
    }
   ]
  },
  {
   "title": "RPO",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_boot_time_seconds{instance=~\"$node\"}",
     "legendFormat": "{{ Environment }}, {{Solution}}"
    }
   ]
  },
  {
   "title": "Criticality",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_boot_time_seconds{instance=~\"$node\"}",
     "legendFormat": "{{ Environment }}, {{Solution}}"
    }
   ]
  },
  {
   "title": "File System",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance='$node',fstype=~\"ext.*|xfs|nfs4\",mountpoint !~\".*pod.*\"} * 100) / node_filesystem_size_bytes{instance='$node',fstype=~\"ext.*|xfs|nfs4\",mountpoint !~\".*pod.*\"})",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$node\", mode='system'})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "description": "Busy state of all CPU cores together (5 min average)\nUpdate query",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"$node\"}) /  count(count(node_cpu_seconds_total{instance=\"$node\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "stat",
   "description": "CPU Load Last 5mins",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load5{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"$node\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{instance=~\"$node\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {instance=~\"$node\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{instance=~\"$node\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{instance=~\"$node\",fstype=~\"ext.?|xfs\"})))by(instance)"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "stat",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\"} - node_memory_SwapFree_bytes{instance=\"$node\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\"} )) * 100"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\"} * 100) / node_memory_MemTotal_bytes{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Platform", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Time Synced",
   "type": "stat",
   "description": "clock synchronized to a reliable server ",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_timex_sync_status{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Backup Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "AddonAzureBackupJobs\n| where JobOperation==\"Backup\"\n| join kind=inner\n(\nCoreAzureBackup\n| where OperationName==\"BackupItem\" and BackupManagementType==\"IaaSVM\"\n| distinct BackupItemUniqueId, BackupItemFriendlyName\n)\non BackupItemUniqueId\n| where TimeGenerated >= now(-24h) and BackupItemFriendlyName==\"$node\"\n| project JobStatus\n",
      "resource": "/subscriptions/7f7bf457-9c8e-4f7f-bb5d-91935342528b/resourceGroups/shp-azlw-rg-n/providers/Microsoft.OperationalInsights/workspaces/SHP-LAW-PaaS-N",
      "resultFormat": "table",
      "workspace": "b46260a5-6c47-4a92-b1b3-1a99fb3a9739"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Compute/virtualMachines",
      "metricNamespace": "Microsoft.Compute/virtualMachines",
      "resourceGroup": "v0-1-0-prd-mngo-rg-c",
      "timeGrain": "",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "query": "", "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "a36e9b76-1c3c-4df3-ae0c-2eca010d4f60",
     "subscriptions": [
      "a36e9b76-1c3c-4df3-ae0c-2eca010d4f60",
      "7f7bf457-9c8e-4f7f-bb5d-91935342528b"
     ]
    }
   ]
  },
  {
   "title": "Cron Jobs",
   "type": "table",
   "description": "Cron Job Status",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "cron_job_exitcode{instance=~\"$node\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "cron_job_duration_seconds{instance=~\"$node\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "(cron_job_finish_time{instance=~\"$node\"} * 1000)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Common Services",
   "type": "stat",
   "description": "Common Services",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{instance=\"$node\",name=~\"chronyd.service|rsyslog.service|crond.service|goferd.service|node_exporter.service|promtail.service|qualys-cloud-agent.service|splunk.service|sshd.service|auditd.service|sshd.service|httpd.service\",state=\"active\"} ",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Systemd Failed",
   "type": "stat",
   "description": "SystemD Failed Units",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_units{instance=\"$node\",state=\"failed\"}"
    }
   ]
  },
  {
   "title": "TCP Estab",
   "type": "stat",
   "description": "TCP Established Connections",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$node\"} - 0"
    }
   ]
  },
  { "title": "Basic Compute/Network/Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode=\"system\",instance=\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "System"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='user',instance=\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "User"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='nice',instance=\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "Nice"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='iowait',instance=\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "Iowait"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$node\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$node\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\"} - node_memory_MemFree_bytes{instance=\"$node\"} - node_memory_Buffers_bytes{instance=\"$node\"} - node_memory_Cached_bytes{instance=\"$node\"} - node_memory_Slab_bytes{instance=\"$node\"} - node_memory_PageTables_bytes{instance=\"$node\"} - node_memory_SwapCached_bytes{instance=\"$node\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=\"$node\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=\"$node\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=\"$node\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$node\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\"}",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\"} - node_memory_SwapFree_bytes{instance=\"$node\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=\"$node\"}",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "description": "The number of bytes read from or written to the device per second",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read bytes"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Written bytes"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "options": {
    "content": "# Note\n\nLoki is not capturing Linux Hostnames. Need to fix this before seting up logs on Dashboard"
   }
  }
 ]
}